# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpectralTools
                                 A QGIS plugin
 Tools for spectral
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-13
        copyright            : (C) 2025 by Lennert Antson
        email                : antsonlennert@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpectralTools class from file SpectralTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spectral_pixel_inspector import SpectralPixelInspector
    return SpectralPixelInspector(iface)
